package com.xuyazhou.mynote.mapper;

import com.xuyazhou.mynote.model.CheckListItem;
import com.xuyazhou.mynote.model.CheckListItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckListItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    long countByExample(CheckListItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    int deleteByExample(CheckListItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    int insert(CheckListItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    int insertSelective(CheckListItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    List<CheckListItem> selectByExampleWithBLOBs(CheckListItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    List<CheckListItem> selectByExample(CheckListItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    CheckListItem selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CheckListItem record, @Param("example") CheckListItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CheckListItem record, @Param("example") CheckListItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CheckListItem record, @Param("example") CheckListItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CheckListItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CheckListItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CheckListItem record);
}