package com.xuyazhou.mynote.mapper;

import com.xuyazhou.mynote.model.Folder;
import com.xuyazhou.mynote.model.FolderExample;
import com.xuyazhou.mynote.model.FolderWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    long countByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int deleteByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int insert(FolderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int insertSelective(FolderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    List<FolderWithBLOBs> selectByExampleWithBLOBs(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    List<Folder> selectByExample(FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    FolderWithBLOBs selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FolderWithBLOBs record, @Param("example") FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FolderWithBLOBs record, @Param("example") FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Folder record, @Param("example") FolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FolderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(FolderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Folder record);
}