package com.xuyazhou.mynote.mapper;

import com.xuyazhou.mynote.model.NoteSyncedJson;

public interface NoteSyncedJsonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_synced_json
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_synced_json
     *
     * @mbg.generated
     */
    int insert(NoteSyncedJson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_synced_json
     *
     * @mbg.generated
     */
    int insertSelective(NoteSyncedJson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_synced_json
     *
     * @mbg.generated
     */
    NoteSyncedJson selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_synced_json
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NoteSyncedJson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note_synced_json
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NoteSyncedJson record);
}