package com.xuyazhou.mynote.mapper;

import com.xuyazhou.mynote.model.TableSeq;
import com.xuyazhou.mynote.model.TableSeqExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TableSeqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    long countByExample(TableSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    int deleteByExample(TableSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    int insert(TableSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    int insertSelective(TableSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    List<TableSeq> selectByExample(TableSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    TableSeq selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TableSeq record, @Param("example") TableSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TableSeq record, @Param("example") TableSeqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TableSeq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_seq
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TableSeq record);


    Integer getSeq(@Param("name") String name);
}