package com.xuyazhou.mynote.model;

import java.io.Serializable;
import java.util.Date;

public class Attachment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.file_type
     *
     * @mbg.generated
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.spath
     *
     * @mbg.generated
     */
    private String spath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment._deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.note_id
     *
     * @mbg.generated
     */
    private String noteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.size
     *
     * @mbg.generated
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attachment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.sid
     *
     * @return the value of attachment.sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.sid
     *
     * @param sid the value for attachment.sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.file_type
     *
     * @return the value of attachment.file_type
     *
     * @mbg.generated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.file_type
     *
     * @param fileType the value for attachment.file_type
     *
     * @mbg.generated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.spath
     *
     * @return the value of attachment.spath
     *
     * @mbg.generated
     */
    public String getSpath() {
        return spath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.spath
     *
     * @param spath the value for attachment.spath
     *
     * @mbg.generated
     */
    public void setSpath(String spath) {
        this.spath = spath == null ? null : spath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.create_time
     *
     * @return the value of attachment.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.create_time
     *
     * @param createTime the value for attachment.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.modified_time
     *
     * @return the value of attachment.modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.modified_time
     *
     * @param modifiedTime the value for attachment.modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment._deleted
     *
     * @return the value of attachment._deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment._deleted
     *
     * @param deleted the value for attachment._deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.note_id
     *
     * @return the value of attachment.note_id
     *
     * @mbg.generated
     */
    public String getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.note_id
     *
     * @param noteId the value for attachment.note_id
     *
     * @mbg.generated
     */
    public void setNoteId(String noteId) {
        this.noteId = noteId == null ? null : noteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.size
     *
     * @return the value of attachment.size
     *
     * @mbg.generated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.size
     *
     * @param size the value for attachment.size
     *
     * @mbg.generated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", fileType=").append(fileType);
        sb.append(", spath=").append(spath);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", noteId=").append(noteId);
        sb.append(", size=").append(size);
        sb.append("]");
        return sb.toString();
    }
}