package com.xuyazhou.mynote.model;

import java.io.Serializable;
import java.util.Date;

public class CheckListItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklistItem.sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklistItem.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklistItem.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklistItem.modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklistItem._deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklistItem.checked
     *
     * @mbg.generated
     */
    private Boolean checked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklistItem._status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklistItem.note_id
     *
     * @mbg.generated
     */
    private String noteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checklistItem.sort_order
     *
     * @mbg.generated
     */
    private String sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklistItem.sid
     *
     * @return the value of checklistItem.sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklistItem.sid
     *
     * @param sid the value for checklistItem.sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklistItem.title
     *
     * @return the value of checklistItem.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklistItem.title
     *
     * @param title the value for checklistItem.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklistItem.create_time
     *
     * @return the value of checklistItem.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklistItem.create_time
     *
     * @param createTime the value for checklistItem.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklistItem.modified_time
     *
     * @return the value of checklistItem.modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklistItem.modified_time
     *
     * @param modifiedTime the value for checklistItem.modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklistItem._deleted
     *
     * @return the value of checklistItem._deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklistItem._deleted
     *
     * @param deleted the value for checklistItem._deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklistItem.checked
     *
     * @return the value of checklistItem.checked
     *
     * @mbg.generated
     */
    public Boolean getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklistItem.checked
     *
     * @param checked the value for checklistItem.checked
     *
     * @mbg.generated
     */
    public void setChecked(Boolean checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklistItem._status
     *
     * @return the value of checklistItem._status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklistItem._status
     *
     * @param status the value for checklistItem._status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklistItem.note_id
     *
     * @return the value of checklistItem.note_id
     *
     * @mbg.generated
     */
    public String getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklistItem.note_id
     *
     * @param noteId the value for checklistItem.note_id
     *
     * @mbg.generated
     */
    public void setNoteId(String noteId) {
        this.noteId = noteId == null ? null : noteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checklistItem.sort_order
     *
     * @return the value of checklistItem.sort_order
     *
     * @mbg.generated
     */
    public String getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checklistItem.sort_order
     *
     * @param sortOrder the value for checklistItem.sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(String sortOrder) {
        this.sortOrder = sortOrder == null ? null : sortOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checklistItem
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", title=").append(title);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", checked=").append(checked);
        sb.append(", status=").append(status);
        sb.append(", noteId=").append(noteId);
        sb.append(", sortOrder=").append(sortOrder);
        sb.append("]");
        return sb.toString();
    }
}