package com.xuyazhou.mynote.model;

import java.io.Serializable;

public class FolderWithBLOBs extends Folder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.order
     *
     * @mbg.generated
     */
    private String order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.sort_type
     *
     * @mbg.generated
     */
    private String sortType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table folder
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.order
     *
     * @return the value of folder.order
     *
     * @mbg.generated
     */
    public String getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.order
     *
     * @param order the value for folder.order
     *
     * @mbg.generated
     */
    public void setOrder(String order) {
        this.order = order == null ? null : order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.sort_type
     *
     * @return the value of folder.sort_type
     *
     * @mbg.generated
     */
    public String getSortType() {
        return sortType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.sort_type
     *
     * @param sortType the value for folder.sort_type
     *
     * @mbg.generated
     */
    public void setSortType(String sortType) {
        this.sortType = sortType == null ? null : sortType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", order=").append(order);
        sb.append(", sortType=").append(sortType);
        sb.append("]");
        return sb.toString();
    }
}