package com.xuyazhou.mynote.model;

import java.io.Serializable;
import java.util.Date;

public class Folder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.note_id
     *
     * @mbg.generated
     */
    private String noteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.Color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.default_folder
     *
     * @mbg.generated
     */
    private Boolean defaultFolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.isLock
     *
     * @mbg.generated
     */
    private Boolean islock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table folder
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.sid
     *
     * @return the value of folder.sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.sid
     *
     * @param sid the value for folder.sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.note_id
     *
     * @return the value of folder.note_id
     *
     * @mbg.generated
     */
    public String getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.note_id
     *
     * @param noteId the value for folder.note_id
     *
     * @mbg.generated
     */
    public void setNoteId(String noteId) {
        this.noteId = noteId == null ? null : noteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.name
     *
     * @return the value of folder.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.name
     *
     * @param name the value for folder.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.Color
     *
     * @return the value of folder.Color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.Color
     *
     * @param color the value for folder.Color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.create_time
     *
     * @return the value of folder.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.create_time
     *
     * @param createTime the value for folder.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.modified_time
     *
     * @return the value of folder.modified_time
     *
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.modified_time
     *
     * @param modifiedTime the value for folder.modified_time
     *
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.deleted
     *
     * @return the value of folder.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.deleted
     *
     * @param deleted the value for folder.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.default_folder
     *
     * @return the value of folder.default_folder
     *
     * @mbg.generated
     */
    public Boolean getDefaultFolder() {
        return defaultFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.default_folder
     *
     * @param defaultFolder the value for folder.default_folder
     *
     * @mbg.generated
     */
    public void setDefaultFolder(Boolean defaultFolder) {
        this.defaultFolder = defaultFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.isLock
     *
     * @return the value of folder.isLock
     *
     * @mbg.generated
     */
    public Boolean getIslock() {
        return islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.isLock
     *
     * @param islock the value for folder.isLock
     *
     * @mbg.generated
     */
    public void setIslock(Boolean islock) {
        this.islock = islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", noteId=").append(noteId);
        sb.append(", name=").append(name);
        sb.append(", color=").append(color);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", deleted=").append(deleted);
        sb.append(", defaultFolder=").append(defaultFolder);
        sb.append(", islock=").append(islock);
        sb.append("]");
        return sb.toString();
    }
}