package com.xuyazhou.mynote.model;

import java.io.Serializable;
import java.util.Date;

public class MemberToken implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_token.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_token.member_id
     *
     * @mbg.generated
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_token.android_token
     *
     * @mbg.generated
     */
    private String androidToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_token.ios_token
     *
     * @mbg.generated
     */
    private String iosToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_token.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_token.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_token
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_token.id
     *
     * @return the value of member_token.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_token.id
     *
     * @param id the value for member_token.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_token.member_id
     *
     * @return the value of member_token.member_id
     *
     * @mbg.generated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_token.member_id
     *
     * @param memberId the value for member_token.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_token.android_token
     *
     * @return the value of member_token.android_token
     *
     * @mbg.generated
     */
    public String getAndroidToken() {
        return androidToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_token.android_token
     *
     * @param androidToken the value for member_token.android_token
     *
     * @mbg.generated
     */
    public void setAndroidToken(String androidToken) {
        this.androidToken = androidToken == null ? null : androidToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_token.ios_token
     *
     * @return the value of member_token.ios_token
     *
     * @mbg.generated
     */
    public String getIosToken() {
        return iosToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_token.ios_token
     *
     * @param iosToken the value for member_token.ios_token
     *
     * @mbg.generated
     */
    public void setIosToken(String iosToken) {
        this.iosToken = iosToken == null ? null : iosToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_token.create_time
     *
     * @return the value of member_token.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_token.create_time
     *
     * @param createTime the value for member_token.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_token.update_time
     *
     * @return the value of member_token.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_token.update_time
     *
     * @param updateTime the value for member_token.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_token
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", androidToken=").append(androidToken);
        sb.append(", iosToken=").append(iosToken);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}