package com.xuyazhou.mynote.model;

import com.xuyazhou.mynote.model.bean.RequestAttachment;
import com.xuyazhou.mynote.model.bean.RequestCheck;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Note implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.note_id
     *
     * @mbg.generated
     */
    private String noteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.modified_time
     *
     * @mbg.generated
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.is_attach
     *
     * @mbg.generated
     */
    private Boolean isAttach;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note._deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.kind
     *
     * @mbg.generated
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.folder_id
     *
     * @mbg.generated
     */
    private String folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table note
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.note_id
     *
     * @return the value of note.note_id
     * @mbg.generated
     */
    public String getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.note_id
     *
     * @param noteId the value for note.note_id
     * @mbg.generated
     */
    public void setNoteId(String noteId) {
        this.noteId = noteId == null ? null : noteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.content
     *
     * @return the value of note.content
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.content
     *
     * @param content the value for note.content
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.create_time
     *
     * @return the value of note.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.create_time
     *
     * @param createTime the value for note.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.modified_time
     *
     * @return the value of note.modified_time
     * @mbg.generated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.modified_time
     *
     * @param modifiedTime the value for note.modified_time
     * @mbg.generated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.is_attach
     *
     * @return the value of note.is_attach
     * @mbg.generated
     */
    public Boolean getIsAttach() {
        return isAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.is_attach
     *
     * @param isAttach the value for note.is_attach
     * @mbg.generated
     */
    public void setIsAttach(Boolean isAttach) {
        this.isAttach = isAttach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note._deleted
     *
     * @return the value of note._deleted
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note._deleted
     *
     * @param deleted the value for note._deleted
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.kind
     *
     * @return the value of note.kind
     * @mbg.generated
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.kind
     *
     * @param kind the value for note.kind
     * @mbg.generated
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.folder_id
     *
     * @return the value of note.folder_id
     * @mbg.generated
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.folder_id
     *
     * @param folderId the value for note.folder_id
     * @mbg.generated
     */
    public void setFolderId(String folderId) {
        this.folderId = folderId == null ? null : folderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.user_id
     *
     * @return the value of note.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.user_id
     *
     * @param userId the value for note.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }


    private RequestAttachment requestAttachment;
    private RequestCheck requestCheck;

    public RequestAttachment getRequestAttachment() {
        return requestAttachment;
    }

    public void setRequestAttachment(RequestAttachment requestAttachment) {
        this.requestAttachment = requestAttachment;
    }

    private List<Attachment> attachmentList = new ArrayList<>();
    private List<CheckListItem> checkListItemList = new ArrayList<>();

    public List<Attachment> getAttachmentList() {
        return attachmentList;
    }

    public void setAttachmentList(List<Attachment> attachmentList) {
        this.attachmentList = attachmentList;
    }

    public List<CheckListItem> getCheckListItemList() {
        return checkListItemList;
    }

    public void setCheckListItemList(List<CheckListItem> checkListItemList) {
        this.checkListItemList = checkListItemList;
    }

    public RequestCheck getRequestCheck() {
        return requestCheck;
    }

    public void setRequestCheck(RequestCheck requestCheck) {
        this.requestCheck = requestCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table note
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", noteId=").append(noteId);
        sb.append(", content=").append(content);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifiedTime=").append(modifiedTime);
        sb.append(", isAttach=").append(isAttach);
        sb.append(", deleted=").append(deleted);
        sb.append(", kind=").append(kind);
        sb.append(", folderId=").append(folderId);
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }
}